In [17]:
# import dependencies
import pandas as pd
import numpy as np
import requests
import json
from pandas.io.json import json_normalize

In [20]:
# Retrive curency exhcange using API for EUR to US conversion of the Value and Wage columns
url = "https://api.darksky.net/forecast/fb0e09b8e9092cef1008bfe2eef00118/33.972386,-84.231986"
response = requests.get(url)
data = response.json()
complete = json_normalize(data['hourly']['data'])

In [21]:
complete.head()

,apparentTemperature,cloudCover,dewPoint,humidity,icon,ozone,precipIntensity,precipProbability,precipType,pressure,summary,temperature,time,uvIndex,visibility,windBearing,windGust,windSpeed
0,42.90,0.0,26.20,0.51,clear-night,310.66,0.0000,0.00,NaN,1026.09,Clear,42.90,1553050800,0,5.04,100,4.04,1.05
1,41.39,0.0,26.26,0.55,clear-night,308.68,0.0000,0.00,NaN,1026.12,Clear,41.39,1553054400,0,4.24,59,4.92,1.84
2,40.50,0.0,26.31,0.57,clear-night,307.84,0.0000,0.00,NaN,1026.22,Clear,40.50,1553058000,0,4.35,55,7.14,2.60
3,38.33,0.0,26.62,0.56,clear-night,307.21,0.0016,0.01,rain,1025.88,Clear,41.03,1553061600,0,10.00,61,9.87,4.21
4,37.29,0.0,26.33,0.56,clear-night,306.76,0.0019,0.01,rain,1025.74,Clear,40.92,1553065200,0,10.00,62,10.54,5.36

In [26]:
# Extracting the subset of values of interest
df = complete.loc[:,["time","temperature","pressure","humidity"]]

df.head()

         time  temperature  pressure  humidity
0  1553050800        42.90   1026.09      0.51
1  1553054400        41.39   1026.12      0.55
2  1553058000        40.50   1026.22      0.57
3  1553061600        41.03   1025.88      0.56
4  1553065200        40.92   1025.74      0.56

In [31]:
# Saving into excel file
df.to_csv("FORCASTING.csv", sep=',', encoding='utf-8')